#! /bin/bash
# 判断 $1 是否为自然数
is_natural_number() {
    if [ $1 -gt 0 ] 2>/dev/null
    then
      return 0  # TRUE
    else 
      return 1  # FALSE
    fi
}

# 判断自然数 $1，是否满足 $2<=$1<=$3
in_range() {
    is_natural_number $1
    if [ $? -eq 0 ]
    then
        if [ $1 -ge $2 -a $1 -le $3 ]
        then
            return 0
        else
            return 1
        fi
    else
        return 1
    fi
}

username=myname
password=mypass
devices_info="devices.txt"
dev_name_array=($(cat ${devices_info} | awk '{print $1}'))
dev_ip_array=($(cat ${devices_info} | awk '{print $2}'))
dev_proto_array=($(cat ${devices_info} | awk '{print $3}'))

devices_count=${#dev_name_array[*]}

while [[ 1 ]]
do
    clear
    echo "请选择要登陆的设备：(输入q退出)"
    for ((i=0; i<$devices_count; i++))
    do
        echo -e "$((i+1)). ${dev_name_array[$i]}\t${dev_ip_array[$i]}\t${dev_proto_array[$i]}"
    done

    read -p "请输入序号： " num

    if [[ -z ${num} ]]
    then
        continue
    fi

    if [ ${num} == 'Q' -o  ${num} == 'q' ]
    then
        echo -e '\n正在退出 ...\n'
        sleep 1
        break
    fi

    in_range ${num} 1 ${devices_count}
    if [ $? == 1 ]
    then
        echo -e '请选择合法序号！'
        sleep 1
        continue
    fi

    num=$((num-1))

    proto=${dev_proto_array[${num}]}
    user=${username}
    host=${dev_ip_array[${num}]}

    ./conn.exp ${proto} ${user} ${host} ${password}

done


